name: tag
run-name: tag
on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_IMAGE_NAME: gitopsdemo
  GH_TOKEN: ${{ github.token }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.11.0
      with:
        project-path: devbox.json

    - name: Release to NPM
      run: |
        devbox run -- ./qowaiv release ${{ github.ref_name }}

    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --generate-notes
    
    