name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm install
    - run: npm build
    - run: npm test
    - uses: ./
      with: 
        milliseconds: 1000
